name: Frontend CI

on:
  push:
    paths:
      - 'frontend/src/**'
      - '.github/workflows/frontend-ci.yml'

  workflow_dispatch:

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: '22.18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint and typecheck
        run: npm run lint:ci

      - name: Run unit & integration tests
        run: npm run test
